### ISSUE TITLE
Type error with nested enums

### ISSUE THREAD

**Issue by maxbechtold** [almondtools/testrecorder#17]
The following reveals a problem with a nested enum (static), leading to a compile error in the generated test. 
The error is that value() returns Object, and the compiler 'cannot convert from Object to Wrapped'.

```java
 File file2 = new GenericObject() {
    Path filePath = null;
    String path = "test.out";
    int prefixLength = 0;
    Wrapped status = Wrapped.enumType("java.io.File$PathStatus", "CHECKED").value();
    }.as(File.class);
```

It is, however, the only error in 3000+ lines of generated code, so hats off!

**Comment by almondtools** [comment]
Thanks for reporting, I created a unit test to reproduce the behaviour.

Apart from the bug - File is also a good candidate that should be handled by a custom serializer/deserializer. Yet documentation on the subject custom serializer/deserializer is short.

**Comment by almondtools** [comment]
The enum problem (along with some other problems) should work now.  Can you verify? Do you need a snapshot in the public maven repository?

**Comment by maxbechtold** [comment]
Currently, no, the test that triggers the snapshot runs into another error, independent of this fix.
I hope I can try it soon.
I'm sorry, but I also spammed this thread with a mistaking pull and push on my fork - probably due to line endings differing (CR/CRLF)...

**Comment by almondtools** [comment]
It seems that two scenarios cause errors with enums:
- enums used as constructor arguments
- enums with a copy constructor (sometimes not visible, generated by JVM)

I will come with some test cases and a solution soon.

**Comment by almondtools** [comment]
There were no new problems with enums so I close this issue.

**Comment by maxbechtold** [comment]
I can confirm it works with testrecorder 0.2.11
